#!/usr/bin/env php
<?php
use Laika\Cli\Application;

// Define App Path & Directory Separator
defined('APP_PATH') || define('APP_PATH', realpath(__DIR__ . '/../../../'));

require APP_PATH . '/lf-boot/app.php';

$app = new Application(APP_PATH);

exit($app->run($argv));
