#!/usr/bin/env php
<?php
use Laika\Cli\Application;

// Define App Path
defined('APP_PATH') || define('APP_PATH', getcwd());

require realpath(__DIR__ . '/../../autoload.php');

// Define App Path
defined('APP_PATH') || define('APP_PATH', getcwd());
defined('DS') || define('DS', DIRECTORY_SEPARATOR);

$app = new Application(APP_PATH);

exit($app->run($argv));
