#!/usr/bin/env php
<?php
require realpath(__DIR__ . '/../../autoload.php');
use Laika\Cli\Application;

// Define App Path
defined('APP_PATH') || define('APP_PATH', getcwd());
defined('DS') || define('DS', DIRECTORY_SEPARATOR);

$app = new Application(APP_PATH);
exit($app->run($argv));
